### ISSUE TITLE
the code is not the implementation of seq2tree

### ISSUE THREAD

**Issue by ZhihaoLZH** [avikdelta/parse_seq2seq#2]
Does the description in the readme.md have any ambiguity？I have read the code which actually show the the implementation of seq2seq model , while the description make me mistaken that  the source code shows seq2tree.

**Comment by avikdelta** [comment]
Yes, you are correct. I have implemented only the sequence-to-sequence+attention parser (as written in the README beginning), not the sequence-to-tree + attention model. Sorry for your confusion. I'll add a note to the README.
